from django.conf.urls import url

#from . import views_design as views
from . import views

urlpatterns = [
	url(r'^view_wechat_token',views.view_wechat_token, name='view_wechat_token'),
	url(r'^view_snd_bonus',views.view_snd_bonus, name='view_snd_bonus'),
	url(r'^view_rcv_bonus',views.view_rcv_bonus, name='view_rcv_bonus'),
	url(r'^view_settle_account',views.view_settle_account, name='view_settle_account'),
	url(r'^view_user_account',views.view_user_account, name='view_user_account'),	
	url(r'^view_redirect_bonus_rcv',views.view_redirect_bonus_rcv, name='view_redirect_bonus_rcv'),
	url(r'^view_geted_bonus',views.view_geted_bonus, name='view_geted_bonus'),
	url(r'^view_ajax_request',views.view_ajax_request, name='view_ajax_request'),
	url(r'^view_redirect_bonus_snd',views.view_redirect_bonus_snd, name='view_redirect_bonus_snd'),
	url(r'^view_common_bonus',views.view_common_bonus, name='view_common_bonus'),
	url(r'^view_random_bonus',views.view_random_bonus, name='view_random_bonus'),	
	url(r'^view_self_rcv_bonus',views.view_self_rcv_bonus, name='view_self_rcv_bonus'),		
	url(r'^view_self_snd_bonus',views.view_self_snd_bonus, name='view_self_snd_bonus'),	
	url(r'^view_self_bonus_list',views.view_self_bonus_list, name='view_self_bonus_list'),		
	url(r'^view_weixin_pay',views.view_weixin_pay, name='view_weixin_pay'),		
	url(r'^view_redirect_settle_account',views.view_redirect_settle_account, name='view_redirect_settle_account'),		
	url(r'^view_redirect_user_account',views.view_redirect_user_account, name='view_redirect_user_account'),	
	url(r'^view_redirect_self_rcv_bonus',views.view_redirect_self_rcv_bonus, name='view_redirect_self_rcv_bonus'),		
	url(r'^view_redirect_self_snd_bonus',views.view_redirect_self_snd_bonus, name='view_redirect_self_snd_bonus'),	
	url(r'^view_redirect_self_bonus_list',views.view_redirect_self_bonus_list, name='view_redirect_self_bonus_list'),	
	url(r'^view_redirect_user_ticket',views.view_redirect_user_ticket, name='view_redirect_user_ticket'),	
	url(r'^view_user_info',views.view_user_info, name='view_user_info'),		
	url(r'^view_user_ticket',views.view_user_ticket, name='view_user_ticket'),	
	url(r'^view_redirect_user_info',views.view_redirect_user_info, name='view_redirect_user_info'),		
	url(r'^view_bonus_detail',views.view_bonus_detail, name='view_bonus_detail'),	
	url(r'^view_redirect_bonus_detail',views.view_redirect_bonus_detail, name='view_redirect_bonus_detail'),
	url(r'^check_consumer_code',views.check_consumer_code, name='check_consumer_code'),	
	url(r'^release_dining_table',views.release_dining_table, name='release_dining_table'),	
	url(r'^view_user_phone',views.view_user_phone, name='view_user_phone'),		
	url(r'^view_user_name',views.view_user_name, name='view_user_name'),	
	url(r'^view_user_address',views.view_user_address, name='view_user_address'),	
	url(r'^view_user_email',views.view_user_email, name='view_user_email'),	
	url(r'^view_user_sex',views.view_user_sex, name='view_user_sex'),	
	url(r'^view_qubaba_forum',views.view_qubaba_forum, name='view_qubaba_forum'),	
	url(r'^view_redirect_qubaba_forum',views.view_redirect_qubaba_forum, name='view_redirect_qubaba_forum'),
	url(r'^pay_notify', views.view_pay_notify, name='pay_notify'),
	url(r'^test_wxpay/pay', views.view_test_wxpay, name='test_wxpay'),
]
