# -*- coding: utf-8 -*-

from __future__ import unicode_literals

weibo_url = 'http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/'

weibos={
u'微笑':'5c/huanglianwx_thumb.gif',
u'嘻嘻':'0b/tootha_thumb.gif',
u'哈哈':'6a/laugh.gif',
u'可爱':'14/tza_thumb.gif',
u'可怜':'af/kl_thumb.gif',
u'挖鼻':'0b/wabi_thumb.gif',
u'吃惊':'f4/cj_thumb.gif',
u'害羞':'6e/shamea_thumb.gif',
u'挤眼':'c3/zy_thumb.gif',
u'闭嘴':'29/bz_thumb.gif',
u'鄙视':'71/bs2_thumb.gif',
u'爱你':'6d/lovea_thumb.gif',
u'泪':'9d/sada_thumb.gif',
u'偷笑':'19/heia_thumb.gif',
u'亲亲':'8f/qq_thumb.gif',
u'生病':'b6/sb_thumb.gif',
u'太开心':'58/mb_thumb.gif',
u'白眼':'d9/landeln_thumb.gif',
u'右哼哼':'98/yhh_thumb.gif',
u'左哼哼':'6d/zhh_thumb.gif',
u'嘘':'a6/x_thumb.gif',
u'衰':'af/cry.gif',
u'委屈':'73/wq_thumb.gif',
u'吐':'9e/t_thumb.gif',
u'哈欠':'cc/haqianv2_thumb.gif',
u'抱抱':'27/bba_thumb.gif',
u'怒':'7c/angrya_thumb.gif',
u'疑问':'5c/yw_thumb.gif',
u'馋嘴':'a5/cza_thumb.gif',
u'拜拜':'70/88_thumb.gif',
u'思考':'e9/sk_thumb.gif',
u'汗':'24/sweata_thumb.gif',
u'困':'40/kunv2_thumb.gif',
u'睡':'96/huangliansj_thumb.gif',
u'钱':'90/money_thumb.gif',
u'失望':'0c/sw_thumb.gif',
u'酷':'40/cool_thumb.gif',
u'色':'20/huanglianse_thumb.gif',
u'哼':'49/hatea_thumb.gif',
u'鼓掌':'36/gza_thumb.gif',
u'晕':'d9/dizzya_thumb.gif',
u'悲伤':'1a/bs_thumb.gif',
u'抓狂':'62/crazya_thumb.gif',
u'黑线':'91/h_thumb.gif',
u'阴险':'6d/yx_thumb.gif',
u'怒骂':'60/numav2_thumb.gif',
u'互粉':'89/hufen_thumb.gif',
u'心':'40/hearta_thumb.gif',
u'伤心':'ea/unheart.gif',
u'猪头':'58/pig.gif',
u'熊猫':'6e/panda_thumb.gif',
u'兔子':'81/rabbit_thumb.gif',
u'ok':'d6/ok_thumb.gif',
u'耶':'d9/ye_thumb.gif',
u'good':'d8/good_thumb.gif',
u'NO':'ae/buyao_org.gif',
u'赞':'d0/z2_thumb.gif',
u'来':'40/come_thumb.gif',
u'弱':'d8/sad_thumb.gif',
u'草泥马':'7a/shenshou_thumb.gif',
u'神马':'60/horse2_thumb.gif',
u'囧':'15/j_thumb.gif',
u'浮云':'bc/fuyun_thumb.gif',
u'给力':'1e/geiliv2_thumb.gif',
u'围观':'f2/wg_thumb.gif',
u'威武':'70/vw_thumb.gif',
u'奥特曼':'bc/otm_thumb.gif',
u'礼物':'c4/liwu_thumb.gif',
u'钟':'d3/clock_thumb.gif',
u'话筒':'9f/huatongv2_thumb.gif',
u'蜡烛':'d9/lazhuv2_thumb.gif',
u'蛋糕':'3a/cakev2_thumb.gif'
}


