# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcvbonus',
            name='message',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
