# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(default='\u5c0f\u660e', max_length=30),
        ),
    ]
