# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='on_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.DiningTable'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.DiningSession'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='recharge_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='rcv_bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.RcvBonus'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='snd_bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.SndBonus'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Ticket'),
        ),
    ]
