# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningtable',
            name='total_money',
        ),
        migrations.AddField(
            model_name='dining',
            name='total_money',
            field=models.FloatField(default=0.0),
        ),
    ]
