# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_rcvbonus_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcvbonus',
            name='message',
        ),
        migrations.AddField(
            model_name='consumer',
            name='latest_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
