# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20160427_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmoney',
            name='price',
            field=models.FloatField(default=10.0),
        ),
    ]
