# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20160507_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
