# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20160504_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletmoney',
            old_name='bonus',
            new_name='snd_bonus',
        ),
        migrations.AddField(
            model_name='ticket',
            name='consume_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_consume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(default=0),
        ),
    ]
