# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_consumer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='own_ticket_num',
            field=models.IntegerField(default=0),
        ),
    ]
