# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20160428_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='on_table',
        ),
        migrations.AlterField(
            model_name='sndbonus',
            name='bonus_type',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='sndbonus',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='rcv_bonus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.RcvBonus'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='recharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Recharge'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Ticket'),
        ),
    ]
