# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_remove_consumer_is_dining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dining',
            name='begin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
