# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0004_auto_20160414_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
