# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0004_auto_20160429_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcvbonus',
            name='bonus_type',
            field=models.IntegerField(default='0'),
        ),
    ]
