# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0004_consumer_own_ticket_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='own_bonus_detail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rcvbonus',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sndbonus',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
