# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0005_auto_20160508_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='sndbonus',
            name='bonus_exhausted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sndbonus',
            name='over_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
