# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0005_consumer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='sex',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
