# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0005_auto_20160506_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumers', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.DiningSession')),
            ],
        ),
    ]
