# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0006_consumersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumersession',
            name='consumers',
        ),
        migrations.AddField(
            model_name='consumersession',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer'),
        ),
    ]
