# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0006_auto_20160508_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sndbonus',
            name='over_time',
        ),
        migrations.AddField(
            model_name='sndbonus',
            name='user_time',
            field=models.IntegerField(default=0),
        ),
    ]
