# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0007_auto_20160507_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeAccountGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_goods', to='weixin.Consumer')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.VirtualMoney')),
            ],
        ),
        migrations.AlterField(
            model_name='recharge',
            name='recharge_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recharge_set', to='weixin.Consumer'),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='recharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_set', to='weixin.Recharge'),
        ),
    ]
