# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0007_auto_20160508_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sndbonus',
            name='user_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
