# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0008_auto_20160509_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='sndbonus',
            name='over_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
