# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0008_auto_20160509_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerAccountGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_goods', to='weixin.Consumer')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.VirtualMoney')),
            ],
        ),
        migrations.RemoveField(
            model_name='consumeaccountgoods',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='consumeaccountgoods',
            name='good',
        ),
        migrations.DeleteModel(
            name='ConsumeAccountGoods',
        ),
    ]
