# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0009_auto_20160509_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
