# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0010_consumer_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_set', to='weixin.Consumer'),
        ),
    ]
