# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0011_auto_20160510_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumeraccountgoods',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='consumeraccountgoods',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='walletmoney',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_set', to='weixin.Consumer'),
        ),
    ]
