# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weixin', '0007_auto_20160507_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(default='\u5145\u503c', max_length=16)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyDetailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('daily_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_set', to='manager.DailyDetail')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.VirtualMoney')),
            ],
        ),
    ]
