# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydetail',
            name='source',
            field=models.CharField(default='\u5145\u503c', max_length=32),
        ),
        migrations.AddField(
            model_name='dailydetail',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
