# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0007_auto_20160507_1108'),
        ('manager', '0002_auto_20160508_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoodStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStatisticsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('consume_value', models.FloatField(default=0)),
                ('charge_value', models.FloatField(default=0)),
                ('account', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='dailydetail',
            name='source',
            field=models.CharField(default='\u7ba1\u7406\u5458\u5145\u503c', max_length=32),
        ),
        migrations.AddField(
            model_name='dailygoodstatistics',
            name='daily_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_set', to='manager.DailyStatisticsRecord'),
        ),
        migrations.AddField(
            model_name='dailygoodstatistics',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.VirtualMoney'),
        ),
    ]
