# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20160508_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailygoodstatistics',
            old_name='action',
            new_name='charge_number',
        ),
        migrations.RenameField(
            model_name='dailygoodstatistics',
            old_name='number',
            new_name='consume_number',
        ),
    ]
