# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20160508_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='action',
            field=models.IntegerField(default=1),
        ),
    ]
