# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20160509_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydetail',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailystatisticsrecord',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
